# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MasterPiano' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MasterPiano
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'React', :path => '../node_modules/react-native', subspecs: [
  'Core',
  'cxxreact',
  'CxxBridge',
  'DevSupport',
  'RCTText',
  'RCTImage',
  'RCTNetwork',
  'RCTActionSheet',
  'RCTAnimation',
  'RCTWebSocket',
]

#pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'
#pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

#pod 'RNSound', :path => '../node_modules/react-native-sound'

pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

pod 'RNFS', :path => '../node_modules/react-native-fs'

target 'MasterPianoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
